### ISSUE TITLE
BUG: Declare and initialize does not work.

### ISSUE THREAD

**Issue by Matt20D** [4115-viz/viz#34]
//test code
   @@x: string = "PLT";
    print("x before re-assignment");
    print(@x);

    print("x after re-assignment");
    @x = "Programming Languages And Translators";
    print(@x);

// output
x before re-assignment
PH�=�
x after re-assignment
Programming Languages And Translators

**Comment by nkw6** [comment]
@@x: string = "PLT";
    print("declaring and assigning variable");
    print("x before re-assignment");
    //print(@x);

    //this works, but throws segmentation fault when calling @x. Must be problem with actually saving value
