### ISSUE TITLE
Bug: Extra bracket throws parse error

### ISSUE THREAD

**Issue by nkw6** [4115-viz/viz#45]
<img width="657" alt="image" src="https://user-images.githubusercontent.com/29387860/163601836-21f9ecc0-2f8d-4f44-bedf-782461c17af2.png">

<img width="540" alt="image" src="https://user-images.githubusercontent.com/29387860/163601887-df79357c-5689-498e-bee9-055670d8ecfb.png">

**Comment by Matt20D** [comment]
that is a valid parser error, no?

**Comment by Matt20D** [comment]
i think this is fine
