### ISSUE TITLE
figure out how to overcome microC limitation with declaring variables

### ISSUE THREAD

**Issue by yanhao-li** [4115-viz/viz#9]
we can only do all variable declarations at the beginning of a program.

This likely has to do with the symbol table and how we assign to it.

alternatively, we can just leave this as a limitation lol

priority: high (although we can worry about this when we get end to end working)

**Comment by yanhao-li** [comment]
I will say let's leave it as a limitation for now.

**Comment by Matt20D** [comment]
This is done, jinsen worked hard to fix. I am closing this one out
